// <auto-generated />
namespace Aplicacion_de_SCRAP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeModificoTicketParaSMT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeModificoTicketParaSMT));
        
        string IMigrationMetadata.Id
        {
            get { return "201809201516459_SeModificoTicketParaSMT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
