// <auto-generated />
namespace Aplicacion_de_SCRAP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deleteNaedDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteNaedDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201810011710295_deleteNaedDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
