#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_de_SCRAP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TraSys")]
	public partial class UsersDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    #endregion
		
		public UsersDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TraSysConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UsersDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuarios
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUsuarios")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iLlave;
		
		private int _iIdNumUsuario;
		
		private string _strNombre;
		
		private string _strPassword;
		
		private int _iIdDepartamento;
		
		private int _iIdPuesto;
		
		private string _strEmail;
		
		private System.Nullable<int> _iIdJefe;
		
		private System.Nullable<int> _iCerrarCaja;
		
		private System.Nullable<int> _iCambiarBatch;
		
		private System.Nullable<int> _iCambiarCombox;
		
		private System.Nullable<int> _iCambiarNaedPruebas;
		
		private System.Nullable<int> _iReImpresionDateCode;
		
		private System.Nullable<int> _iIdAreaTiempoMuerto;
		
		private System.Nullable<int> _iImprimeDateCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniLlaveChanging(int value);
    partial void OniLlaveChanged();
    partial void OniIdNumUsuarioChanging(int value);
    partial void OniIdNumUsuarioChanged();
    partial void OnstrNombreChanging(string value);
    partial void OnstrNombreChanged();
    partial void OnstrPasswordChanging(string value);
    partial void OnstrPasswordChanged();
    partial void OniIdDepartamentoChanging(int value);
    partial void OniIdDepartamentoChanged();
    partial void OniIdPuestoChanging(int value);
    partial void OniIdPuestoChanged();
    partial void OnstrEmailChanging(string value);
    partial void OnstrEmailChanged();
    partial void OniIdJefeChanging(System.Nullable<int> value);
    partial void OniIdJefeChanged();
    partial void OniCerrarCajaChanging(System.Nullable<int> value);
    partial void OniCerrarCajaChanged();
    partial void OniCambiarBatchChanging(System.Nullable<int> value);
    partial void OniCambiarBatchChanged();
    partial void OniCambiarComboxChanging(System.Nullable<int> value);
    partial void OniCambiarComboxChanged();
    partial void OniCambiarNaedPruebasChanging(System.Nullable<int> value);
    partial void OniCambiarNaedPruebasChanged();
    partial void OniReImpresionDateCodeChanging(System.Nullable<int> value);
    partial void OniReImpresionDateCodeChanged();
    partial void OniIdAreaTiempoMuertoChanging(System.Nullable<int> value);
    partial void OniIdAreaTiempoMuertoChanged();
    partial void OniImprimeDateCodeChanging(System.Nullable<int> value);
    partial void OniImprimeDateCodeChanged();
    #endregion
		
		public tblUsuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iLlave", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int iLlave
		{
			get
			{
				return this._iLlave;
			}
			set
			{
				if ((this._iLlave != value))
				{
					this.OniLlaveChanging(value);
					this.SendPropertyChanging();
					this._iLlave = value;
					this.SendPropertyChanged("iLlave");
					this.OniLlaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iIdNumUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int iIdNumUsuario
		{
			get
			{
				return this._iIdNumUsuario;
			}
			set
			{
				if ((this._iIdNumUsuario != value))
				{
					this.OniIdNumUsuarioChanging(value);
					this.SendPropertyChanging();
					this._iIdNumUsuario = value;
					this.SendPropertyChanged("iIdNumUsuario");
					this.OniIdNumUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strNombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strNombre
		{
			get
			{
				return this._strNombre;
			}
			set
			{
				if ((this._strNombre != value))
				{
					this.OnstrNombreChanging(value);
					this.SendPropertyChanging();
					this._strNombre = value;
					this.SendPropertyChanged("strNombre");
					this.OnstrNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPassword", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string strPassword
		{
			get
			{
				return this._strPassword;
			}
			set
			{
				if ((this._strPassword != value))
				{
					this.OnstrPasswordChanging(value);
					this.SendPropertyChanging();
					this._strPassword = value;
					this.SendPropertyChanged("strPassword");
					this.OnstrPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iIdDepartamento", DbType="Int NOT NULL")]
		public int iIdDepartamento
		{
			get
			{
				return this._iIdDepartamento;
			}
			set
			{
				if ((this._iIdDepartamento != value))
				{
					this.OniIdDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._iIdDepartamento = value;
					this.SendPropertyChanged("iIdDepartamento");
					this.OniIdDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iIdPuesto", DbType="Int NOT NULL")]
		public int iIdPuesto
		{
			get
			{
				return this._iIdPuesto;
			}
			set
			{
				if ((this._iIdPuesto != value))
				{
					this.OniIdPuestoChanging(value);
					this.SendPropertyChanging();
					this._iIdPuesto = value;
					this.SendPropertyChanged("iIdPuesto");
					this.OniIdPuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strEmail", DbType="VarChar(50)")]
		public string strEmail
		{
			get
			{
				return this._strEmail;
			}
			set
			{
				if ((this._strEmail != value))
				{
					this.OnstrEmailChanging(value);
					this.SendPropertyChanging();
					this._strEmail = value;
					this.SendPropertyChanged("strEmail");
					this.OnstrEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iIdJefe", DbType="Int")]
		public System.Nullable<int> iIdJefe
		{
			get
			{
				return this._iIdJefe;
			}
			set
			{
				if ((this._iIdJefe != value))
				{
					this.OniIdJefeChanging(value);
					this.SendPropertyChanging();
					this._iIdJefe = value;
					this.SendPropertyChanged("iIdJefe");
					this.OniIdJefeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCerrarCaja", DbType="Int")]
		public System.Nullable<int> iCerrarCaja
		{
			get
			{
				return this._iCerrarCaja;
			}
			set
			{
				if ((this._iCerrarCaja != value))
				{
					this.OniCerrarCajaChanging(value);
					this.SendPropertyChanging();
					this._iCerrarCaja = value;
					this.SendPropertyChanged("iCerrarCaja");
					this.OniCerrarCajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCambiarBatch", DbType="Int")]
		public System.Nullable<int> iCambiarBatch
		{
			get
			{
				return this._iCambiarBatch;
			}
			set
			{
				if ((this._iCambiarBatch != value))
				{
					this.OniCambiarBatchChanging(value);
					this.SendPropertyChanging();
					this._iCambiarBatch = value;
					this.SendPropertyChanged("iCambiarBatch");
					this.OniCambiarBatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCambiarCombox", DbType="Int")]
		public System.Nullable<int> iCambiarCombox
		{
			get
			{
				return this._iCambiarCombox;
			}
			set
			{
				if ((this._iCambiarCombox != value))
				{
					this.OniCambiarComboxChanging(value);
					this.SendPropertyChanging();
					this._iCambiarCombox = value;
					this.SendPropertyChanged("iCambiarCombox");
					this.OniCambiarComboxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iCambiarNaedPruebas", DbType="Int")]
		public System.Nullable<int> iCambiarNaedPruebas
		{
			get
			{
				return this._iCambiarNaedPruebas;
			}
			set
			{
				if ((this._iCambiarNaedPruebas != value))
				{
					this.OniCambiarNaedPruebasChanging(value);
					this.SendPropertyChanging();
					this._iCambiarNaedPruebas = value;
					this.SendPropertyChanged("iCambiarNaedPruebas");
					this.OniCambiarNaedPruebasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iReImpresionDateCode", DbType="Int")]
		public System.Nullable<int> iReImpresionDateCode
		{
			get
			{
				return this._iReImpresionDateCode;
			}
			set
			{
				if ((this._iReImpresionDateCode != value))
				{
					this.OniReImpresionDateCodeChanging(value);
					this.SendPropertyChanging();
					this._iReImpresionDateCode = value;
					this.SendPropertyChanged("iReImpresionDateCode");
					this.OniReImpresionDateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iIdAreaTiempoMuerto", DbType="Int")]
		public System.Nullable<int> iIdAreaTiempoMuerto
		{
			get
			{
				return this._iIdAreaTiempoMuerto;
			}
			set
			{
				if ((this._iIdAreaTiempoMuerto != value))
				{
					this.OniIdAreaTiempoMuertoChanging(value);
					this.SendPropertyChanging();
					this._iIdAreaTiempoMuerto = value;
					this.SendPropertyChanged("iIdAreaTiempoMuerto");
					this.OniIdAreaTiempoMuertoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iImprimeDateCode", DbType="Int")]
		public System.Nullable<int> iImprimeDateCode
		{
			get
			{
				return this._iImprimeDateCode;
			}
			set
			{
				if ((this._iImprimeDateCode != value))
				{
					this.OniImprimeDateCodeChanging(value);
					this.SendPropertyChanging();
					this._iImprimeDateCode = value;
					this.SendPropertyChanged("iImprimeDateCode");
					this.OniImprimeDateCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
